name: PlatformIO CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs:
          [
            SIM800L_IP5306_VERSION_20190610,
            SIM800L_AXP192_VERSION_20200327,
            SIM800C_AXP192_VERSION_20200609,
            SIM800L_IP5306_VERSION_20200811,
            T-A7670X,
            T-Call-A7670X-V1-0,
            T-Call-A7670X-V1-1,
            T-A7608X
          ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update PIP cache on every commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ github.run_id }}
          restore-keys: pip # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Update PlatformIO cache on every commit
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: platformio-${{ github.run_id }}
          restore-keys: platformio # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Update Build cache on every commit
        uses: actions/cache@v4
        with:
          path: .pio/
          key: build-${{ github.run_id }}
          restore-keys: build # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Update generated-files cache on every commit
        uses: actions/cache@v4
        with:
          path: |
            .pio/build/${{ matrix.envs }}/firmware.bin
            .pio/build/${{ matrix.envs }}/partitions.bin
            .pio/build/${{ matrix.envs }}/bootloader.bin
            .pio/build/${{ matrix.envs }}/littlefs.bin
          key: generated-files-${{ github.run_id }}-${{ matrix.envs }}
          restore-keys: generated-files # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build Firmware
        run: pio run -e ${{ matrix.envs }}

      - name: Build Filesystem
        run: pio run --target buildfs -e ${{ matrix.envs }}

  #########################################################################################
  ## Build Package
  #########################################################################################
  package:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        envs:
          [
            SIM800L_IP5306_VERSION_20190610,
            SIM800L_AXP192_VERSION_20200327,
            SIM800C_AXP192_VERSION_20200609,
            SIM800L_IP5306_VERSION_20200811,
            T-A7670X,
            T-Call-A7670X-V1-0,
            T-Call-A7670X-V1-1,
            T-A7608X
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Update generated-files cache on every commit
        uses: actions/cache@v4
        with:
          path: |
            .pio/build/${{ matrix.envs }}/firmware.bin
            .pio/build/${{ matrix.envs }}/partitions.bin
            .pio/build/${{ matrix.envs }}/bootloader.bin
            .pio/build/${{ matrix.envs }}/littlefs.bin
          key: generated-files-${{ github.run_id }}-${{ matrix.envs }}
          restore-keys: generated-files # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Update package cache on every commit
        uses: actions/cache@v4
        with:
          path: package
          key: package-${{ github.run_id }}-${{ matrix.envs }}
          restore-keys: package # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Set Variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch="$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1/") >> $GITHUB_OUTPUT

      - name: Prepare package*.zip artifact
        run: |
          rm -rf package
          mkdir -p package
          rm -rf package/*.zip
          cp -f ".pio/build/${{ matrix.envs }}/firmware.bin" "package/firmware.bin"
          cp -f ".pio/build/${{ matrix.envs }}/bootloader.bin" "package/bootloader.bin"
          cp -f ".pio/build/${{ matrix.envs }}/partitions.bin" "package/partitions.bin"
          cp -f ".pio/build/${{ matrix.envs }}/littlefs.bin" "package/partitions.bin"
          cd ./package

      - name: Upload package.zip artifact (Firmware + Bootloader + Partitions + LittleFS)
        uses: actions/upload-artifact@v4
        with:
          name: "OBD2-MQTT-${{ matrix.envs }}-${{ steps.vars.outputs.branch }}_(${{ steps.vars.outputs.sha_short }})"
          path: ./package

  #########################################################################################
  ## Prepare and create release
  #########################################################################################
  prepare-release:
    runs-on: ubuntu-latest
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        envs:
          [
            #            SIM800L_IP5306_VERSION_20190610,
            #            SIM800L_AXP192_VERSION_20200327,
            #            SIM800C_AXP192_VERSION_20200609,
            #            SIM800L_IP5306_VERSION_20200811,
            #            T-A7670X,
            T-Call-A7670X-V1-0,
            #            T-Call-A7670X-V1-1,
            #            T-A7608X
          ]

    # Sets permissions of the GITHUB_TOKEN to allow updating the branches
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Update package cache on every commit
        uses: actions/cache@v4
        with:
          path: package
          key: package-${{ github.run_id }}-${{ matrix.envs }}
          restore-keys: package # This matches above key as it is only used as a prefix. it the restores the nearest cache, see https://github.com/restore-keys:/blob/main/tips-and-workarounds.md#update-a-cache

      - name: Set Variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch="$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1/") >> $GITHUB_OUTPUT

      - name: Prepare artifacts for release
        run: |
          rm -rf release
          mkdir -p release
          cd ../package
          zip -r ../release/OBD2-MQTT-${{ matrix.envs }}-${{ steps.vars.outputs.branch }}.zip .
